sudo: false
language: android
jdk:
  - oraclejdk8
env:
  - PITEST_REGRESSION_TESTS=latestOnly
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter platform-tools
  - echo y|android update sdk --all --no-ui --force --filter tools
  - echo y|android update sdk --all --no-ui --force --filter build-tools-25.0.0
  - echo y|android update sdk --all --no-ui --force --filter android-25
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - mkdir -p $ANDROID_HOME/licenses/
  - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license

install: ./gradlew assemble
script: ./gradlew funcTest check --stacktrace --info --continue

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_failure:
  - cat build/test/info.solidsoft.gradle.pitest.functional.PitestPluginFunctional1Spec/setup-and-run-simple-build-on-pitest-infrastructure/build/outputs/lint-results-debug.xml