sudo: false
language: android
jdk:
  - oraclejdk8
env:
  - PITEST_REGRESSION_TESTS=latestOnly
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25

install: ./gradlew assemble
script: ./gradlew funcTest check --stacktrace --info --continue -Pcompatibility

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/